-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 23:05:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_locacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_locacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_locacao` DEFAULT CHARACTER SET utf8 ;
USE `db_locacao` ;

-- -----------------------------------------------------
-- Table `db_locacao`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `telefone1` VARCHAR(15) NOT NULL,
  `telefone2` VARCHAR(15) NULL,
  `email1` VARCHAR(45) NOT NULL,
  `email2` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `tipoEndereco` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(150) NULL,
  `cidade` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `numero` INT NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `ie` VARCHAR(45) NULL,
  `tipoCliente` VARCHAR(15) NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`obra` (
  `idObra` INT NOT NULL AUTO_INCREMENT,
  `codObra` INT NOT NULL,
  `respObra` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(15) NOT NULL,
  `telefone2` VARCHAR(15) NULL,
  `email1` VARCHAR(45) NOT NULL,
  `email2` VARCHAR(45) NULL,
  `complemento` VARCHAR(150) NULL,
  `tipoEndereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `bairro` VARCHAR(20) NOT NULL,
  `numero` INT NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idObra`),
  CONSTRAINT `fk_obra_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `db_locacao`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`contrato` (
  `idContrato` INT NOT NULL AUTO_INCREMENT,
  `dtEmissao` DATETIME NOT NULL,
  `dtAprovacao` DATE NOT NULL,
  `custoEntrega` FLOAT NOT NULL,
  `custoRetirada` FLOAT NOT NULL,
  `notas` VARCHAR(100) NULL,
  `valorAluguel` FLOAT NOT NULL,
  `dtInicio` DATETIME NOT NULL,
  `dtFim` DATE NOT NULL,
  `statusOrcamento` TINYINT NOT NULL,
  `codContrato` INT NOT NULL,
  `obra_idObra` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idContrato`),
  CONSTRAINT `fk_contrato_obra1`
    FOREIGN KEY (`obra_idObra`)
    REFERENCES `db_locacao`.`obra` (`idObra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`fatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`fatura` (
  `idFatura` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` VARCHAR(20) NOT NULL,
  `diaVencimento` DATE NOT NULL,
  `especCobranca` VARCHAR(60) NULL,
  `valorTotal` FLOAT NOT NULL,
  `dtEmissao` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `valorFrete` FLOAT NULL,
  `adicional` VARCHAR(100) NULL,
  `abservacoes` VARCHAR(100) NULL,
  `dtEnvio` DATE NOT NULL,
  `numNF` INT NOT NULL,
  `numBoletoInt` INT NOT NULL,
  `numBoletoBanco` INT NOT NULL,
  `valorPago` FLOAT NOT NULL,
  `dtPagamento` DATE NOT NULL,
  `dtVerificacao` DATE NOT NULL,
  `contrato_idcontrato` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFatura`),
  CONSTRAINT `fk_fatura_contrato1`
    FOREIGN KEY (`contrato_idcontrato`)
    REFERENCES `db_locacao`.`contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `db_locacao`.`aditamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`aditamento` (
  `idAditamento` INT NOT NULL AUTO_INCREMENT,
  `diaVencimento` INT NOT NULL,
  `diaSemana` INT NULL,
  `semanaMes` INT NULL,
  `status` TINYINT NOT NULL,
  `seqAditamento` INT NOT NULL,
  `contrato_idContrato` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAditamento`),
  CONSTRAINT `fk_aditamento_contrato1`
    FOREIGN KEY (`contrato_idContrato`)
    REFERENCES `db_locacao`.`contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone1` VARCHAR(15) NOT NULL,
  `telefone2` VARCHAR(15) NULL,
  `email1` VARCHAR(45) NOT NULL,
  `email2` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`container`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`container` (
  `idContainer` INT NOT NULL,
  `numContainer` INT NOT NULL,
  `medida` FLOAT NOT NULL,
  `tipoPorta` VARCHAR(45) NULL,
  `janelaLat` INT NULL,
  `janelaCirc` INT NULL,
  `forrado` TINYINT NULL,
  `eletrificado` TINYINT NOT NULL,
  `tomada` INT NULL,
  `lampada` INT NULL,
  `entradaAC` INT NULL,
  `sanitario` INT NULL,
  `chuveiro` TINYINT NULL,
  `dtCadastro` DATETIME NULL,
  PRIMARY KEY (`idContainer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `containers` TINYINT NULL,
  `equipEletrico` TINYINT NULL,
  `equipMecanico` TINYINT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  `valorCompra` FLOAT NOT NULL,
  `valorAluguel` FLOAT NOT NULL,
  `status` TINYINT NOT NULL,
  `dtFabricacao` DATE NULL,
  `vlBaseAluguel` FLOAT NOT NULL,
  `tipo` VARCHAR(60) NOT NULL,
  `anotacoes` VARCHAR(100) NULL,
  `fornecedor_idFornecedor` INT NOT NULL,
  `container_idContainer` INT NOT NULL,
  `categoria_idCategoria` INT NOT NULL,
  `dtCadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProduto`),
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_idFornecedor`)
    REFERENCES `db_locacao`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_container1`
    FOREIGN KEY (`container_idContainer`)
    REFERENCES `db_locacao`.`container` (`idContainer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_idCategoria`)
    REFERENCES `db_locacao`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(60) NOT NULL,
  `funcao` VARCHAR(45) NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `administrador` TINYINT NOT NULL,
  `foto` VARCHAR(100) NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`historicoAluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`historicoAluguel` (
  `idHistoricoAluguel` INT NOT NULL AUTO_INCREMENT,
  `dtInicio` DATETIME NOT NULL,
  `dtFinal` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `contrato_idContrato` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idHistoricoAluguel`),
  CONSTRAINT `fk_contrato_has_produto_contrato2`
    FOREIGN KEY (`contrato_idContrato`)
    REFERENCES `db_locacao`.`contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_has_produto_produto2`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `db_locacao`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_locacao`.`historicoAluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_locacao`.`historicoAluguel` (
  `idHistoricoAluguel` INT NOT NULL AUTO_INCREMENT,
  `dtInicio` DATETIME NOT NULL,
  `dtFinal` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  `contrato_idContrato` INT NOT NULL,
  `produto_idProduto` INT NOT NULL,
  `dtCadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idHistoricoAluguel`),
  CONSTRAINT `fk_contrato_has_produto_contrato2`
    FOREIGN KEY (`contrato_idContrato`)
    REFERENCES `db_locacao`.`contrato` (`idContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_has_produto_produto2`
    FOREIGN KEY (`produto_idProduto`)
    REFERENCES `db_locacao`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
